### ISSUE TITLE
As a client I would like to buy coin with USD

### ISSUE THREAD

**Issue by oihanaelizagoyen** [AsierAlba10/cryptocurrency-api#1]
**Description**
Generate an API call for buying a coin with USD.

**Example**

> _Happy path:_

> - Request: POST api/coin/buy

>- Body:
{
  "coin_id": "string",
  "wallet_id": "string",
  "amount_usd": 0
}

> - Response: 200 successful operation

```
{ ‘successful ’ : 'Successful operation’}
```

> _Missing coin_id:_

> - Request: POST api/coin/buy

>- Body:
{
  "wallet_id": "string",
  "amount_usd": 0
}

> - Response: 400 coin_id mandatory.

```
{ ‘error’ : ‘coin_id mandatory.’}
```

> _Missing wallet_id:_

> - Request: POST api/coin/buy

>- Body:
{
  "coin_id": "string",
  "amount_usd": 0
}

> - Response: 400 wallet_id mandatory.

```
{ ‘error’ : ‘wallet_id mandatory.’}
```

> _Missing amount_usd:_

> - Request: POST api/coin/buy

>- Body:
{
  "coin_id": "string",
  "wallet_id": "string"
}

> - Response: 400 amount_usd mandatory.

```
{ ‘error’ : ‘amount_usdmandatory.’}
```

> _Coin id doesn't exist:_

> - Request: POST api/coin/buy

>- Body:
{
  "coin_id": "invalid_id",
  "wallet_id": "string",
  "amount_usd": 0
}

> - Response: 404 A coin with the specified ID was not found.

```
{ ‘error’ : ‘A coin with the specified ID was not found.’}
```

> _Wallet id doesn't exist:_

> - Request: POST api/coin/buy

>- Body:
{
  "coin_id": "string",
  "wallet_id": "invalid_id",
  "amount_usd": 0
}

> - Response: 404 A wallet with the specified ID was not found.

```
{ ‘error’ : ‘A wallet with the specified ID was not found.’}
```

> _Service unavailable:_

> - Request:  POST api/coin/buy

>- Body:
{
  "coin_id": "string",
  "wallet_id": "string",
  "amount_usd": 0
}

> - Response: 503 Service unavailable

```
{ 'error' : ‘Service unavailable’}
```

**Comment by AsierAlba10** [comment]
Issue Finalized
