### ISSUE TITLE
As a client I would like to open a new wallet

### ISSUE THREAD

**Issue by oihanaelizagoyen** [AsierAlba10/cryptocurrency-api#3]
**Description**
Generate an API call for opening a new wallet.

**Example**

> _Happy path:_

> - Request: POST /wallet/open

> - Response: 200 successful operation

```

{ 'successful' : ‘Successful operation’}

```

> _Service unavailable:_

> - Request:  POST /wallet/open

> - Response: 503 Service unavailable

```
{ 'error' : ‘Service unavailable’}
```

**Comment by AsierAlba10** [comment]
Issue Finalized
