### ISSUE TITLE
As a client I would like to get given coin status

### ISSUE THREAD

**Issue by oihanaelizagoyen** [AsierAlba10/cryptocurrency-api#5]
**Description**
Generate an API call for getting given coin status.

**Example**

> _Happy path:_

> - Request: GET /coin/status/1

> - Response: 200 successful operation

```
{
  "coin_id": "1",
  "symbol": "string",
  "name": "string",
  "name_id": "string",
  "rank": 0,
  "price_usd": "string"
}
```

> _Coin id doesn't exist:_

> - Request: GET /coin/status/-1

> - Response: 404 A coin with the specified ID was not found.

```
{ ‘error’ : ‘A coin with the specified ID was not found.’}
```

> _Service unavailable:_

> - Request: GET /coin/status/1

> - Response: 503 Service unavailable

```
{ 'error' : ‘Service unavailable’}
```

**Comment by AsierAlba10** [comment]
Issue Finalized
